server:
    port: 9000
    
datasource:
    platform: postgres
    url: jdbc:postgresql://localhost/bigdata
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


spring.jpa.generate-ddl: true